name: build
on:
  workflow_dispatch:
jobs:
  build:
    timeout-minutes: 360
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Prepare
        timeout-minutes: 360
        run: |
          cd ~
          git clone https://github.com/Willie169/latexindent-termux.git
          cd latexindent-termux
          git clone https://github.com/cmhughes/latexindent.pl.git
          cd latexindent.pl
          sed -i -r 's,eval\s\"use\sUnicode::GCString\"\sif\s\$switches\{GCString\},use Unicode::GCString,' latexindent.pl
          chmod 777 latexindent.pl
          chmod 777 .
      - name: Run build.sh
        timeout-minutes: 360
        run: |
          docker run --rm -v "$HOME/latexindent-termux:/data/data/com.termux/files/home/latexindent-termux" -w "/data/data/com.termux/files/home/latexindent-termux" --privileged termux/termux-docker bash -c '
            set -euxo pipefail
            echo "deb https://packages.termux.dev/apt/termux-main stable main" > /data/data/com.termux/files/usr/etc/apt/sources.list
            ./build.sh
          '
      - uses: actions/upload-artifact@v6
        with:
          name: latexindent
          path: latexindent-termux/latexindent.pl/latexindent
